# This rule is not used by the project janus itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over backup.janus.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: janus
    app.kubernetes.io/managed-by: kustomize
  name: backupcontract-admin-role
rules:
- apiGroups:
  - backup.janus.io
  resources:
  - backupcontracts
  verbs:
  - '*'
- apiGroups:
  - backup.janus.io
  resources:
  - backupcontracts/status
  verbs:
  - get
