# permissions for end users to view transactions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: janus
    app.kubernetes.io/managed-by: kustomize
  name: transaction-viewer-role
rules:
- apiGroups:
  - backup.janus.io
  resources:
  - transactions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.janus.io
  resources:
  - transactions/status
  verbs:
  - get
