apiVersion: backup.janus.io/v1alpha1
kind: Backup
metadata:
  labels:
    app.kubernetes.io/name: janus
    app.kubernetes.io/managed-by: kustomize
  name: backup-sample
spec:
  # TODO(user): Add fields here
