## Append samples of your project ##
resources:
- transaction_sample.yaml
- transaction_create.yaml
- transaction_patch.yaml
- transaction_delete.yaml
- transaction_multi.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
